version: '3.8'

services:
  web:
    build: .
    command: uvicorn parser_api.main:app --host localhost --port 8000
    volumes:
      - app_logs:/var/log/app
    ports:
      - "8000:8000" 
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=${DB_PATH}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_SYSTEM=postgresql
      - DB_DRIVER=asyncpg
    env_file: .env.docker
    depends_on:
      db:
        condition: service_healthy
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        tag: "parser-api"

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: ${DB_PATH}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_PATH}"]
      interval: 5s
      timeout: 5s
      retries: 5
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  postgres_data:
  app_logs: