"""Initial migration from models

Revision ID: 5994220904a6
Revises: 
Create Date: 2025-08-08 19:25:58.875085

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from sqlalchemy.ext.declarative import declarative_base
from src.parser_api.infrastructure.db.models import Base


# revision identifiers, used by Alembic.
revision: str = '5994220904a6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Products',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('photos', sa.JSON(), nullable=True),
    sa.Column('price_basic', sa.Integer(), nullable=True),
    sa.Column('price_with_discount', sa.Integer(), nullable=True),
    sa.Column('discount_size', sa.Integer(), nullable=True),
    sa.Column('quantity_rate', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('options', sa.JSON(), nullable=True),
    sa.Column('category_name', sa.String(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('store_name', sa.String(), nullable=True),
    sa.Column('store_id', sa.Integer(), nullable=True),
    sa.Column('query', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Products')
    # ### end Alembic commands ###
