"""Change product.id to BIGINT

Revision ID: 695ed86140ce
Revises: c38e0a36b483
Create Date: 2025-07-31 17:55:40.577383

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from sqlalchemy.ext.declarative import declarative_base
from parser_api.infrastructure.db.models import Base


# revision identifiers, used by Alembic.
revision: str = '695ed86140ce'
down_revision: Union[str, Sequence[str], None] = 'c38e0a36b483'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
