"""Initial migration

Revision ID: edf8ff69866e
Revises: 
Create Date: 2025-07-31 17:48:45.538735

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from sqlalchemy.ext.declarative import declarative_base
from parser_api.infrastructure.db.models import Base


# revision identifiers, used by Alembic.
revision: str = 'edf8ff69866e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Products', sa.Column('id', sa.Integer(), nullable=False))
    op.add_column('Products', sa.Column('name', sa.String(), nullable=False))
    op.add_column('Products', sa.Column('photos', sa.JSON(), nullable=True))
    op.add_column('Products', sa.Column('price_basic', sa.Integer(), nullable=True))
    op.add_column('Products', sa.Column('price_with_discount', sa.Integer(), nullable=True))
    op.add_column('Products', sa.Column('discount_size', sa.Integer(), nullable=True))
    op.add_column('Products', sa.Column('quantity_rate', sa.Integer(), nullable=True))
    op.add_column('Products', sa.Column('description', sa.String(), nullable=True))
    op.add_column('Products', sa.Column('options', sa.JSON(), nullable=True))
    op.add_column('Products', sa.Column('category_name', sa.String(), nullable=True))
    op.add_column('Products', sa.Column('category_id', sa.Integer(), nullable=True))
    op.add_column('Products', sa.Column('store_name', sa.String(), nullable=True))
    op.add_column('Products', sa.Column('store_id', sa.Integer(), nullable=True))
    op.add_column('Products', sa.Column('query', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Products', 'query')
    op.drop_column('Products', 'store_id')
    op.drop_column('Products', 'store_name')
    op.drop_column('Products', 'category_id')
    op.drop_column('Products', 'category_name')
    op.drop_column('Products', 'options')
    op.drop_column('Products', 'description')
    op.drop_column('Products', 'quantity_rate')
    op.drop_column('Products', 'discount_size')
    op.drop_column('Products', 'price_with_discount')
    op.drop_column('Products', 'price_basic')
    op.drop_column('Products', 'photos')
    op.drop_column('Products', 'name')
    op.drop_column('Products', 'id')
    # ### end Alembic commands ###
